x-environment: &default-environment
  PUID: ${PUID}
  TZ: ${TZ}

x-common: &common
  restart: unless-stopped

services:
  gluetun:
    <<: *common
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # other ports
      - 8080:8080 # qbitorrent
      - 6881:6881 # qbitorrent
      - 6881:6881/udp # qbitorrent
    volumes:
      - ${DOCKERCONFDIR}/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      <<: [*default-environment]
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: wireguard
      # OpenVPN:
      # OPENVPN_USER:
      # OPENVPN_PASSWORD:
      # Wireguard:
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
      SERVER_REGIONS: France
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      # UPDATER_PERIOD:

  jackett:
    <<: *common
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      <<: [*default-environment]
      AUTO_UPDATE: true #optional
      # RUN_OPTS: #optional
    volumes:
      - ${DOCKERCONFDIR}/jackett:/config
    ports:
      - 9117:9117

  lidarr:
    <<: *common
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      <<: [*default-environment]
    volumes:
      - ${DOCKERCONFDIR}/lidarr:/config
      - ${DOCKERSTORAGEDIR}:/shared
      # - /path/to/music:/music #optional
    ports:
      - 8686:8686

  overseerr:
    <<: *common
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      <<: [*default-environment]
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFDIR}/overseerr:/app/config

  plex:
    <<: *common
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      <<: [*default-environment]
      VERSION: docker
      # PLEX_CLAIM: https://plex.tv/claim #optional
    volumes:
      - ${DOCKERCONFDIR}/plex:/config
      - ${DOCKERSTORAGEDIR}/media:/shared/media

  plextraktsync:
    <<: *common
    image: lscr.io/linuxserver-labs/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - ${DOCKERCONFDIR}/plextraktsync:/config
    environment:
      <<: [*default-environment]

  qbittorrent:
    <<: *common
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: [*default-environment]
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${DOCKERCONFDIR}/qbittorrent:/config
      - ${DOCKERSTORAGEDIR}:/shared
    depends_on:
      - gluetun
    network_mode: "service:gluetun"

  radarr:
    <<: *common
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/shared
    ports:
      - 7878:7878
    environment:
      <<: [*default-environment]

  sonarr:
    <<: *common
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/shared
    ports:
      - 8989:8989
    environment:
      <<: [*default-environment]
